/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * API Index
     * @description Returns API information and available endpoints
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description API Index Information */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ApiIndex"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health Check
     * @description Returns the health status of the API
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Health Check Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["HealthCheck"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/logs/by-path": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get API logs by specific path
     * @description Retrieve API logs filtered by a specific path with enhanced performance optimization. Requires x-api-key header for authentication.
     */
    get: {
      parameters: {
        query: {
          /** @description The exact path to filter logs by (e.g., '/v1/auth/signin') */
          path: string;
          page?: number;
          limit?: number;
          /** @description HTTP method filter */
          method?: string;
          /** @description HTTP status code filter */
          statusCode?: number | null;
          /** @description Filter logs from this date */
          fromDate?: string;
          /** @description Filter logs to this date */
          toDate?: string;
        };
        header: {
          /** @description API key for logs access */
          "x-api-key": string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description API logs filtered by path */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["LogsByPathResponse"];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized - Invalid or missing API key */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/logs/test": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Test API key validation
     * @description A simple endpoint to test if the x-api-key header is valid. Returns success message if API key is correct.
     */
    get: {
      parameters: {
        query?: never;
        header: {
          /** @description API key for logs access */
          "x-api-key": string;
        };
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description API key is valid */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["TestApiKeyResponse"];
          };
        };
        /** @description Unauthorized - Invalid or missing API key */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/logs/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get API log details
     * @description Retrieve detailed information for a specific API log entry. Requires x-api-key header for authentication.
     */
    get: {
      parameters: {
        query?: never;
        header: {
          /** @description API key for logs access */
          "x-api-key": string;
        };
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description API log details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["LogDetail"];
          };
        };
        /** @description Unauthorized - Invalid or missing API key */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Log not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/signup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["SignUpRequest"];
        };
      };
      responses: {
        /** @description User registration with workspace creation */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SignUpResponse"];
          };
        };
        /** @description Bad request - validation errors */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description User already exists */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/signin": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["SignInRequest"];
        };
      };
      responses: {
        /** @description Successful authentication. Returns user information, authentication tokens, default workspace details, and user profile within that workspace. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SignInResponse"];
          };
        };
        /** @description Authentication failed - invalid email or password */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description User account exists but has no access to any workspace, or associated workspace not found */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/signout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description User logout - refresh token cookie is automatically cleared */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SignOutResponse"];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Token refreshed successfully. Returns user information and updated session details. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["RefreshResponse"];
          };
        };
        /** @description Invalid, expired, or missing session token */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description User account is not verified or access is forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/forgot-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ForgotPasswordRequest"];
        };
      };
      responses: {
        /** @description Password reset request */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ForgotPasswordResponse"];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/reset-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ResetPasswordRequest"];
        };
      };
      responses: {
        /** @description Password reset confirmation */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ResetPasswordResponse"];
          };
        };
        /** @description Bad request - invalid token or passwords don't match */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/verify-email": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["VerifyEmailRequest"];
        };
      };
      responses: {
        /** @description Email verification successful */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["VerifyEmailResponse"];
          };
        };
        /** @description Invalid verification token */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/send-verification-email": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["SendVerificationEmailRequest"];
        };
      };
      responses: {
        /** @description Verification email sent successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SendVerificationEmailResponse"];
          };
        };
        /** @description Failed to send verification email */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/passkey/list": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of user's passkeys */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["PasskeyListResponse"];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/passkey/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Passkey ID to update */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["PasskeyUpdateRequest"];
        };
      };
      responses: {
        /** @description Passkey updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["PasskeyUpdateResponse"];
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Passkey not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Passkey ID to delete */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Passkey deleted successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              success: boolean;
            };
          };
        };
        /** @description Authentication required */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Passkey not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ApiIndex: {
      message: string;
      version: string;
      documentation: string;
      endpoints: {
        health: string;
        docs: string;
        reference: string;
        logs: string;
      };
    };
    HealthCheck: {
      status: string;
      timestamp: string;
      uptime: number;
      version: string;
    };
    LogItem: {
      /** Format: uuid */
      id: string;
      method: string;
      url: string;
      path: string;
      statusCode?: number;
      duration?: number;
      userAgent?: string;
      ipAddress?: string;
      /** Format: uuid */
      userId?: string;
      /** Format: uuid */
      workspaceId: string;
      errorMessage?: string;
      createdAt: string;
      requestHeaders?: {
        [key: string]: string;
      } | null;
      requestBody?: unknown;
      responseBody?: unknown;
      responseHeaders?: {
        [key: string]: string;
      } | null;
    };
    Pagination: {
      page: number;
      limit: number;
      total: number;
      pages: number;
    };
    LogsByPathResponse: {
      data: components["schemas"]["LogItem"][];
      pagination: components["schemas"]["Pagination"];
      summary: {
        path: string;
        totalRequests: number;
        method?: string;
        statusCode?: number;
      };
    };
    TestApiKeyResponse: {
      success: boolean;
      message: string;
      timestamp: string;
    };
    BaseApiLog: {
      /** Format: uuid */
      workspaceId: string;
      /** Format: uuid */
      userId?: string;
      method: string;
      url: string;
      path: string;
      statusCode?: number;
      duration?: number;
      userAgent?: string;
      ipAddress?: string;
      errorMessage?: string;
      requestHeaders?: {
        [key: string]: string;
      } | null;
      requestBody?: unknown;
      responseBody?: unknown;
      responseHeaders?: {
        [key: string]: string;
      } | null;
    };
    LogDetail: components["schemas"]["BaseApiLog"] & {
      /** Format: uuid */
      id: string;
      createdAt: string;
      updatedAt: string;
    };
    /** @description Created user information */
    User: {
      /**
       * Format: uuid
       * @description Unique user identifier
       */
      id: string;
      /** @description User's full name */
      name: string;
      /**
       * Format: email
       * @description User's email address
       */
      email: string;
      /** @description Whether the user's email has been verified */
      emailVerified: boolean;
      /** @description User's profile image URL */
      image: string | null;
      /** @description ISO timestamp when the user was created */
      createdAt: string;
      /** @description ISO timestamp when the user was last updated */
      updatedAt: string;
    };
    /** @description Authentication session */
    Session: {
      /**
       * Format: uuid
       * @description Session identifier
       */
      id: string;
      /** @description Session token */
      token: string;
      /** @description ISO timestamp when the session expires */
      expiresAt: string;
      /** @description IP address of the session */
      ipAddress: string | null;
      /** @description User agent of the session */
      userAgent: string | null;
      /**
       * Format: uuid
       * @description User ID associated with the session
       */
      userId: string;
      /** @description ISO timestamp when the session was created */
      createdAt: string;
      /** @description ISO timestamp when the session was last updated */
      updatedAt: string;
    } | null;
    SignUpResponse: {
      user: components["schemas"]["User"];
      session: components["schemas"]["Session"];
    };
    SignUpRequest: {
      /** @description User's full name */
      name: string;
      /**
       * Format: email
       * @description User's email address
       */
      email: string;
      /** @description Password (minimum 6 characters) */
      password: string;
      /** @description Password (minimum 6 characters) */
      confirmPassword: string;
      /** @description Optional profile image URL */
      image?: string | "";
    };
    SignInResponse: {
      user: components["schemas"]["User"] & unknown;
      session: components["schemas"]["Session"];
    };
    /** @example {
     *       "email": "john.doe@example.com",
     *       "password": "securePassword123"
     *     } */
    SignInRequest: {
      /**
       * Format: email
       * @description User's email address
       */
      email: string;
      /** @description Password (minimum 6 characters) */
      password: string;
    };
    SignOutResponse: {
      success: boolean;
    };
    RefreshResponse: {
      user: components["schemas"]["User"] & unknown;
      session: components["schemas"]["Session"] & unknown;
    };
    ForgotPasswordResponse: {
      success: boolean;
      message: string;
    };
    ForgotPasswordRequest: {
      /** Format: email */
      email: string;
    };
    ResetPasswordResponse: {
      success: boolean;
    };
    ResetPasswordRequest: {
      /** @description Password (minimum 6 characters) */
      newPassword: string;
      /** @description Password (minimum 6 characters) */
      confirmPassword: string;
    };
    VerifyEmailResponse: {
      success: boolean;
      message: string;
    };
    VerifyEmailRequest: {
      /** @description Authentication token */
      token: string;
    };
    SendVerificationEmailResponse: {
      success: boolean;
      message: string;
    };
    SendVerificationEmailRequest: {
      /** Format: email */
      email: string;
    };
    Passkey: {
      /** @description Passkey identifier */
      id: string;
      /** @description Passkey name */
      name: string | null;
      /** @description ISO timestamp when the passkey was created */
      createdAt: string;
      /** @description Device type (single_device or multi_device) */
      deviceType: string;
      /** @description Whether the passkey is backed up */
      backedUp: boolean;
    };
    PasskeyListResponse: {
      passkeys: components["schemas"]["Passkey"][];
    };
    PasskeyUpdateResponse: {
      success: boolean;
      passkey: components["schemas"]["Passkey"];
    };
    PasskeyUpdateRequest: {
      /** @description New name for the passkey */
      name: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
