import type * as React from 'react'
import { cn } from '@/lib/utils'

/**
 * Figma-style squircle path in objectBoundingBox (0–1) units.
 *
 * Generated by Lisse's squircle math — https://github.com/JaceThings/Lisse
 * (@lisse/core, MIT © Jace Attard) — via generatePath(1, 1, { radius: 0.25,
 * smoothing: 0.6 }). Re-run the generator and replace this constant to change
 * curvature; see ./squircle.md.
 */
const SQUIRCLE_PATH =
  'M 0.4000 0 L 0.6000 0 c 0.1400 0 0.2100 0 0.2635 0.0272 a 0.2500 0.2500 0 0 1 0.1093 0.1093 c 0.0272 0.0535 0.0272 0.1235 0.0272 0.2635 L 1.0000 0.4000 L 1.0000 0.6000 c 0 0.1400 0 0.2100 -0.0272 0.2635 a 0.2500 0.2500 0 0 1 -0.1093 0.1093 c -0.0535 0.0272 -0.1235 0.0272 -0.2635 0.0272 L 0.6000 1.0000 L 0.4000 1.0000 c -0.1400 0 -0.2100 0 -0.2635 -0.0272 a 0.2500 0.2500 0 0 1 -0.1093 -0.1093 c -0.0272 -0.0535 -0.0272 -0.1235 -0.0272 -0.2635 L 0 0.6000 L 0 0.4000 c 0 -0.1400 0 -0.2100 0.0272 -0.2635 a 0.2500 0.2500 0 0 1 0.1093 -0.1093 c 0.0535 -0.0272 0.1235 -0.0272 0.2635 -0.0272 Z'

// why: shared id across instances — the def is static, so duplicate ids are
// harmless (browsers use the first match); unique ids would only buy churn.
const CLIP_ID = 'squircle-clip'

interface SquircleProps extends React.ComponentProps<'div'> {
  /**
   * Square dimension (number → px, or any CSS length). The fixed curve
   * scales with the box, so this is the one knob for sizing:
   * `<Squircle size={96}>`. Omit to size via className instead.
   */
  size?: number | string
}

/**
 * Container clipped to a squircle. Curve scales with the element via
 * objectBoundingBox units, so it is geometrically true on squares (avatars,
 * icons) and distorts on non-square boxes. Don't combine with `rounded-*`
 * utilities; put box-shadows on a wrapper (clip-path clips them).
 */
function Squircle({ className, style, size, ...props }: SquircleProps) {
  return (
    <>
      <svg
        width="0"
        height="0"
        aria-hidden="true"
        style={{ position: 'absolute', overflow: 'hidden' }}
      >
        <defs>
          <clipPath id={CLIP_ID} clipPathUnits="objectBoundingBox">
            <path d={SQUIRCLE_PATH} />
          </clipPath>
        </defs>
      </svg>
      <div
        data-slot="squircle"
        className={cn(className)}
        // why: clipPath after the style spread — overriding it silently breaks
        // the component, so the user style prop must not win here
        style={{
          ...(size !== undefined ? { width: size, height: size } : undefined),
          ...style,
          clipPath: `url(#${CLIP_ID})`,
        }}
        {...props}
      />
    </>
  )
}

export { Squircle, SQUIRCLE_PATH }
