/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplateRouteImport } from './routes/template'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthDemoRouteImport } from './routes/health-demo'
import { Route as IndexRouteImport } from './routes/index'

const TemplateRoute = TemplateRouteImport.update({
  id: '/template',
  path: '/template',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthDemoRoute = HealthDemoRouteImport.update({
  id: '/health-demo',
  path: '/health-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health-demo': typeof HealthDemoRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/template': typeof TemplateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health-demo': typeof HealthDemoRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/template': typeof TemplateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health-demo': typeof HealthDemoRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/template': typeof TemplateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/health-demo' | '/login' | '/signup' | '/template'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/health-demo' | '/login' | '/signup' | '/template'
  id: '__root__' | '/' | '/health-demo' | '/login' | '/signup' | '/template'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthDemoRoute: typeof HealthDemoRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TemplateRoute: typeof TemplateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/template': {
      id: '/template'
      path: '/template'
      fullPath: '/template'
      preLoaderRoute: typeof TemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-demo': {
      id: '/health-demo'
      path: '/health-demo'
      fullPath: '/health-demo'
      preLoaderRoute: typeof HealthDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthDemoRoute: HealthDemoRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TemplateRoute: TemplateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
